import Link from "next/link";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-2xl mx-auto">
        <Link
          href="/login"
          className="text-sm text-blue-600 hover:underline mb-6 inline-block"
        >
          &larr; Back to Sign In
        </Link>

        <div className="bg-white rounded-2xl shadow-lg p-8">
          <h1 className="text-2xl font-bold mb-6">Terms of Service</h1>
          <p className="text-sm text-gray-500 mb-8">
            Last updated: February 23, 2026
          </p>

          <div className="space-y-6 text-sm text-gray-700 leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing or using Memchat, you agree to be bound by these
                Terms of Service. If you do not agree to these terms, do not
                use the service.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                2. Service Description
              </h2>
              <p>
                Memchat is an AI-powered assistant that provides:
              </p>
              <ul className="list-disc pl-5 space-y-1 mt-2">
                <li>Text-based conversations with an AI assistant</li>
                <li>Real-time voice interactions</li>
                <li>Document upload and analysis</li>
                <li>
                  RAG (Retrieval-Augmented Generation) memory that uses your
                  past conversations and documents to provide contextual
                  responses
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                3. User Responsibilities
              </h2>
              <ul className="list-disc pl-5 space-y-1">
                <li>
                  You must provide accurate account information.
                </li>
                <li>
                  You are responsible for maintaining the security of your
                  account credentials.
                </li>
                <li>
                  You agree not to use the service for any unlawful purpose or
                  to transmit harmful, abusive, or objectionable content.
                </li>
                <li>
                  You agree not to attempt to disrupt, overload, or interfere
                  with the operation of the service.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                4. Intellectual Property
              </h2>
              <p>
                You retain ownership of content you submit to Memchat. By
                using the service, you grant us a limited license to process
                your content as necessary to provide the service (e.g.,
                generating embeddings, sending messages to AI providers).
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                5. AI-Generated Content
              </h2>
              <p>
                Responses generated by the AI assistant are provided
                &ldquo;as is&rdquo; for informational purposes. AI-generated
                content may be inaccurate, incomplete, or outdated. You should
                not rely on AI responses as professional, legal, medical, or
                financial advice.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                6. Limitation of Liability
              </h2>
              <p>
                Memchat is provided &ldquo;as is&rdquo; and &ldquo;as
                available&rdquo; without warranties of any kind. To the
                maximum extent permitted by law, we shall not be liable for
                any indirect, incidental, special, consequential, or punitive
                damages arising from your use of the service.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                7. Termination
              </h2>
              <p>
                We reserve the right to suspend or terminate your access to
                the service at any time for violation of these terms or for
                any other reason at our discretion. You may delete your
                account at any time by contacting us.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                8. Changes to Terms
              </h2>
              <p>
                We may update these terms from time to time. Continued use of
                the service after changes constitutes acceptance of the
                revised terms. We will make reasonable efforts to notify users
                of significant changes.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                9. Contact
              </h2>
              <p>
                For questions about these terms, contact us at{" "}
                <a
                  href="mailto:support@cyberiad.ai"
                  className="text-blue-600 hover:underline"
                >
                  support@cyberiad.ai
                </a>
                .
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
